---
title: "How many tree species in French Guiana Tropical Moist Forest?"
author:
  - name: "Eric Marcon"
  - name: "et al."
abstract: >
  Abstract of the article.
date: "`r format(Sys.time(), '%d %B %Y')`"
url: https://GitHubID.github.io/Repository/
github-repo: GitHubID/Repository
lang: en-US
bibliography: references.bib
biblio-style: chicago
preamble: >
  \hyphenation{bio-di-ver-si-ty sap-lings}
pdftoc: false
toc-depth: 3
always_allow_html: yes
output:
  bookdown::html_document2:
    toc: yes
    toc_float: yes
  rmdformats::downcute:
    use_bookdown: yes
    lightbox: yes
  bookdown::word_document2: default
  bookdown::gitbook:
    config:
      download: "pdf"
      sharing:
        github: yes
  bookdown::pdf_book:
    template: latex/template.tex
    citation_package: natbib
    latex_engine: xelatex
    keep_tex: yes
---

```{r DoNotModify, include=FALSE}
### Utilities. Do not modify.
# Installation of packages if necessary
InstallPackages <- function(Packages) {
  InstallPackage <- function(Package) {
    if (!Package %in% installed.packages()[, 1]) {
      install.packages(Package, repos="https://cran.rstudio.com/")
    }
  }
  invisible(sapply(Packages, InstallPackage))
}

# Basic packages
InstallPackages(c("bookdown", "formatR", "kableExtra", "ragg"))

# kableExtra must be loaded 
if (knitr::opts_knit$get("rmarkdown.pandoc.to") == "docx") {
  # Word output (https://stackoverflow.com/questions/35144130/in-knitr-how-can-i-test-for-if-the-output-will-be-pdf-or-word)
  # Do not use autoformat (https://github.com/haozhu233/kableExtra/issues/308)
  options(kableExtra.auto_format = FALSE)
}
library("kableExtra")

# Chunk font size hook: allows size='small' or any valid Latex font size in chunk options
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
```

```{r Options, include=FALSE}
### Customized options for this document
# Add necessary packages here
Packages <- c("ade4", "dbmss", "secret", "tidyverse")
# Install them
InstallPackages(Packages)

# knitr options
knitr::opts_chunk$set(
  cache=FALSE, # Cache chunk results
  echo = TRUE, # Show/Hide R chunks
  warning=FALSE, # Show/Hide warnings
  messages=FALSE, # Show/Hide messages
  # Figure alignment and size
  fig.align='center', out.width='80%',
  # Graphic devices (ragg_png is better than standard png)
  dev = c("ragg_png", "pdf"),
  # Code chunk format
  tidy=TRUE, tidy.opts=list(blank=FALSE, width.cutoff=50),
  size="scriptsize", knitr.graphics.auto_pdf = TRUE
  )
options(width=50)

# ggplot style
library("tidyverse", "ade4")
theme_set(theme_bw())
theme_update(panel.background=element_rect(fill="transparent", colour=NA),
             plot.background=element_rect(fill="transparent", colour=NA))
knitr::opts_chunk$set(dev.args=list(bg="transparent"))

# Random seed
set.seed(973)
```

# Introduction

# Methods

Self-similarity [@Harte1999; @Harte1999a].

Estimation of the richness of an Indian forest [@Krishnamani2004].

## Data

```{r}
# Decrypt the vault
library("secret") %>% suppressMessages()
name_project <- "GF-Richness"
vault <- "vault"
Sys.setenv(USER_KEY = usethis::proj_path(paste0(name_project, ".rsa")))
Plots <- get_secret("Plots", vault = vault)
Abundances <- get_secret("Abundances", vault = vault)
```


# Results

## Plots

## Random plot

One plot per location

```{r}
# One plot per location...
Plots %>% 
  mutate(Random=runif(n())) -> 
  RandomizedPlots
RandomizedPlots %>% 
  group_by(Location) %>%
  summarize(MaxRandom=max(Random)) %>% 
  rename(Random=MaxRandom) %>% 
  inner_join(RandomizedPlots) %>% 
  select(Plot) -> 
  SelectedPlots

# ...or all plots
SelectedPlots <- Plots["Plot"]

# Distances
library("dbmss") %>% suppressMessages()
Plots %>% 
  inner_join(SelectedPlots) %>%
  rename(PointName=Plot, X=X_UTM, Y=Y_UTM, PointType=Location) %>% 
  mutate(PointWeight=1) %>% 
  wmppp(unitname = c("meter", "meters")) %>% 
  pairdist() %>% 
  as.dist -> 
  Distances
```


## Sorensen

```{r}
library("ade4") %>% suppressMessages()
Abundances %>% 
  inner_join(SelectedPlots) %>% 
  select(-Plot) %>% 
  dist.binary(method = 5) -> Sorensen
Sorensen <- 1-Sorensen
```

## Relation

```{r}
plot(log10(Sorensen) ~ log10(Distances))
# Régression linéaire, à partir de 1km de distance
summary(regression <- lm(log10(Sorensen)[log10(Distances)>3] ~ log10(Distances)[log10(Distances)>3]))
abline(a=regression$coefficients[1], b=regression$coefficients[2], col="red")
# z
(z <- -regression$coefficients[2]/2)
```

## Extrapolation

```{r}
# Extrapolation de Paracou : .625km², 604 sp > c=631
(c <- 600/.625^z)
# Nombre d'espèces total
(spsim <- c*80000^z)
```

## Fisher

```{r}
# Nombre d'arbres
Ntrees <- 8*10^6 * mean(colSums(Abundances[, -1]))
# Taux de couverture par placette
###########################
library("entropart") %>% suppressMessages()
C <- apply(Abundances[, -1], 1, function(X) Coverage(X))
# Distribution de probabilités, corrigée par les taux de couverture
ObsProba <- C %*% as.matrix(Abundances[, -1]/rowSums(Abundances[, -1]))/nrow(Abundances)
plot(as.ProbaVector(ObsProba))
# Abondances
EstimatedAbd <- as.AbdVector(round(ObsProba*Ntrees, 0))
# 50% centraux
EA50 <- as.AbdVector(sort(EstimatedAbd, decreasing = T)[round(length(EstimatedAbd)/4):round(length(EstimatedAbd)*3/4)])
x <- 1:length(EA50)
y <- as.numeric(log(EA50))
# Régression rang-abondance sur la partie rectiligne de la courbe
EA50lm <- lm(y ~ x)
# Nombre d'espèces extrapolé
NbSpecies <- round(-EA50lm$coefficients[1]/EA50lm$coefficients[2]) + round(length(EstimatedAbd)/4)-1
# Régression de la partie rectiligne
plot(y~x, ylim=c(0,max(y)))
summary(EA50lm)
abline(a=EA50lm$coefficients[1], b=EA50lm$coefficients[2], col="red")
# Metacommunauté complète: partie observée
EA75 <- sort(EstimatedAbd, decreasing = T)[1:round(length(EstimatedAbd)*3/4)]
plot(EstimatedAbd, ylim=c(1, max(EA75)), xlim=c(0, NbSpecies), col="grey")
points(EA75, ylim=c(1, max(EA75)), xlim=c(0,-EA50lm$coefficients[1]/EA50lm$coefficients[2]))
Extra <- exp(EA50lm$coefficients[1])*cumprod(rep(exp(EA50lm$coefficients[2]), NbSpecies-round(length(EstimatedAbd)/4)+1))
lines(x=round(length(EstimatedAbd)/4):NbSpecies, y=Extra, col="red")
# Vérification : effectif total
(Ntotal <- sum(EA75) + sum(Extra[(length(EA75)-NbSpecies+length(Extra)+1):length(Extra)]))
# Ajustement d'une log-série
plot(as.AbdVector(round(c(EA75, Extra[(length(EA75)-NbSpecies+length(Extra)+1):length(Extra)]))), Distribution = "lseries")
# Nombre d'espèces estimées
NbSpecies
```

## Hyperdominance

```{r}
# Hyperdominance
EstimatedAbd <- sort(round(ObsProba*Ntrees, 0), decreasing = TRUE)
plot(cumsum(EstimatedAbd), ylim=c(0, Ntrees))
abline(h=Ntrees/2, lty=2, col="red")
hdSpecies <- min(which(cumsum(EstimatedAbd)>Ntrees/2))
abline(v=hdSpecies, lty=2, col="red")
```


`r if (!knitr:::is_latex_output()) '# References {-}'`
